version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-prod

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  api_app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_api_app
    command: ["/fastapi_app/docker/api_app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  web_app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_web_app
    command: ["/fastapi_app/docker/web_app.sh"]
    ports:
      - 9998:8000
    depends_on:
      - api_app

  celery:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
  
volumes:
  db-data:
      name: ${DATABASE_VOLUME}
