version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-prod

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  api_app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_api_app
    command: ["/fastapi_app/docker/api_app.sh"]
    ports:
      - 9999:8000
    expose:
      - 8000
    depends_on:
      - db
      - redis

  web_app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_web_app
    command: ["/fastapi_app/docker/web_app.sh"]
    ports:
      - 9998:8000
    expose:
      - 8000
    depends_on:
      - api_app

  celery:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - web_app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - web_app


volumes:
  db-data:
      name: ${DATABASE_VOLUME}
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data
