"""task edit history

Revision ID: 4c95b4929b48
Revises: f8c01f5945f1
Create Date: 2023-11-08 09:49:13.084515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c95b4929b48'
down_revision: Union[str, None] = 'f8c01f5945f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('previous_assignee_id', sa.Integer(), nullable=False),
        sa.Column('new_assignee_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['new_assignee_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['previous_assignee_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_history')
    # ### end Alembic commands ###
