"""scopes

Revision ID: dd1fcee4f1b6
Revises: f8b2de93c168
Create Date: 2023-11-15 15:44:51.902725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1fcee4f1b6'
down_revision: Union[str, None] = 'f8b2de93c168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_user', sa.Column('scopes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth2_user', 'scopes')
    # ### end Alembic commands ###
